# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Relational Network

[advisories]
ignore = [
    "RUSTSEC-2025-0141", # bincode unmaintained; transitive via Solana; waiting on upstream fix
    "RUSTSEC-2025-0134", # rustls-pemfile 2.2.0 unmaintained
]